name: Build and Release

on:
  push:
    paths:
      - 'src/**'
      - 'Cargo.toml'
      - 'Cargo.lock'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # ratchet:actions/checkout@v4.2.2

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config musl-tools musl-dev
          sudo apt-get install -y --no-install-recommends

      - name: Install musl-openssl
        run: |
          OPENSSL_VERSION=3.5.0
          wget https://www.openssl.org/source/openssl-$OPENSSL_VERSION.tar.gz
          tar xvf openssl-$OPENSSL_VERSION.tar.gz
          cd openssl-$OPENSSL_VERSION
          CC=musl-gcc ./Configure no-shared no-async --prefix=/usr/local/musl --openssldir=/usr/local/musl linux-x86_64
          make -j$(nproc)
          sudo make install
          echo "OPENSSL_DIR=/usr/local/musl" >> $GITHUB_ENV
          echo "OPENSSL_STATIC=1" >> $GITHUB_ENV

      - name: Setup Rust
        uses: actions-rs/toolchain@b2417cde72dcf67f306c0ae8e0828a81bf0b189f # ratchet:actions-rs/toolchain@v1.0.6
        with:
          toolchain: stable
          target: x86_64-unknown-linux-musl

      - name: Build Release Binary
        run: |
          cargo build --release --target x86_64-unknown-linux-musl
          strip target/x86_64-unknown-linux-musl/release/azure-devops-admins

      - name: Create Release
        uses: softprops/action-gh-release@c95fe1489396fe8a9eb87c0abf8aa5b2ef267fda # ratchet:softprops/action-gh-release@v2.2.1
        with:
          files: target/x86_64-unknown-linux-musl/release/azure-devops-admins

      - name: Upload Binary as Artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # ratchet:actions/upload-artifact@v4.6.2
        with:
          name: azure-devops-admins
          path: target/x86_64-unknown-linux-musl/release/azure-devops-admins
