name: Build and Release

on:
  push:
    paths:
      - 'src/**'
      - 'Cargo.toml'
      - 'Cargo.lock'
      - '.github/workflows/build-release.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # ratchet:actions/checkout@v4.2.2

      - uses: cachix/install-nix-action@d1ca217b388ee87b2507a9a93bf01368bde7cec2 # ratchet:cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-24.11

      - name: Build with Nix
        run: |
          nix-build -E '
            with import <nixpkgs> {};
            let
              staticOpenssl = pkgs.pkgsStatic.openssl;
            in
            rustPlatform.buildRustPackage {
              pname = "azure-devops-admins";
              version = "0.1.0";
              src = ./.;
              cargoLock.lockFile = ./Cargo.lock;
              nativeBuildInputs = [ pkg-config ];
              buildInputs = [ staticOpenssl ];
              OPENSSL_STATIC = "1";
              OPENSSL_DIR = "${staticOpenssl}";
              RUSTFLAGS = "-C target-feature=+crt-static";
              CARGO_BUILD_TARGET = "x86_64-unknown-linux-musl";
            }'
          cp result/bin/azure-devops-admins .

      - name: Upload Binary as Artifact
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # ratchet:actions/upload-artifact@v4.6.2
        with:
          name: azure-devops-admins
          path: azure-devops-admins
