name: Build and Release

on:
  push:
    paths:
      - 'src/**'
      - 'Cargo.toml'
      - 'Cargo.lock'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v4.1.1

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config=0.29.2-1ubuntu3 musl-tools=1.2.3-1 musl-dev=1.2.3-1
          sudo apt-get install -y --no-install-recommends libssl-dev=3.0.2-0ubuntu1.12
          
      - name: Install musl-openssl
        run: |
          OPENSSL_VERSION=3.0.2
          wget https://www.openssl.org/source/openssl-$OPENSSL_VERSION.tar.gz
          tar xvf openssl-$OPENSSL_VERSION.tar.gz
          cd openssl-$OPENSSL_VERSION
          CC=musl-gcc ./Configure no-shared no-async --prefix=/usr/local/musl --openssldir=/usr/local/musl linux-x86_64
          make -j$(nproc)
          sudo make install
          echo "OPENSSL_DIR=/usr/local/musl" >> $GITHUB_ENV
          echo "OPENSSL_STATIC=1" >> $GITHUB_ENV

      - name: Setup Rust
        uses: actions-rs/toolchain@v1.0.7
        with:
          toolchain: stable
          target: x86_64-unknown-linux-musl

      - name: Build Release Binary
        run: |
          cargo build --release --target x86_64-unknown-linux-musl
          strip target/x86_64-unknown-linux-musl/release/azure-devops-admins

      - name: Create Release
        uses: softprops/action-gh-release@v1.1.0
        with:
          files: target/x86_64-unknown-linux-musl/release/azure-devops-admins
          
      - name: Upload Binary as Artifact
        uses: actions/upload-artifact@v4.3.1
        with:
          name: azure-devops-admins
          path: target/x86_64-unknown-linux-musl/release/azure-devops-admins 