name: Build and Release

on:
  push:
    paths:
      - 'src/**'
      - 'Cargo.toml'
      - 'Cargo.lock'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v4.1.1

      - name: Install OpenSSL
        run: |
          sudo apt-get update
          sudo apt-get install -y pkg-config=0.29.2-1ubuntu3 libssl-dev=3.0.2-0ubuntu1.12

      - name: Setup Rust
        uses: actions-rs/toolchain@v1.0.7
        with:
          toolchain: stable
          target: x86_64-unknown-linux-musl

      - name: Build Release Binary
        run: |
          cargo build --release --target x86_64-unknown-linux-musl
          strip target/x86_64-unknown-linux-musl/release/azure-devops-admins

      - name: Create Release
        uses: softprops/action-gh-release@v1.1.0
        with:
          files: target/x86_64-unknown-linux-musl/release/azure-devops-admins
          
      - name: Upload Binary as Artifact
        uses: actions/upload-artifact@v4.3.1
        with:
          name: azure-devops-admins
          path: target/x86_64-unknown-linux-musl/release/azure-devops-admins 