name: Check Azure DevOps Admins

on:
  schedule:
    - cron: '0 8 * * 1'  # Jeden Montag um 8:00 UTC
  workflow_dispatch:  # Erlaubt manuelle Ausführung

jobs:
  check-admins:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read
    
    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build and run admin checker
        env:
          AZURE_DEVOPS_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}
        run: |
          cargo run > new_content.txt
          if ! diff index.adoc new_content.txt > /dev/null; then
            echo "ADMINS_CHANGED=true" >> $GITHUB_ENV
          fi

      - name: Check for existing issues
        if: env.ADMINS_CHANGED == 'true'
        uses: actions/github-script@v7
        with:
          script: |
            const issues = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              labels: ['admin-list-update']
            });
            
            if (issues.data.length === 0) {
              const fs = require('fs');
              const newContent = fs.readFileSync('new_content.txt', 'utf8');
              
              await github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: 'Azure DevOps Admin List Update Required',
                body: `Die Liste der Azure DevOps Administratoren hat sich geändert.
                
                Neue Version:
                \`\`\`asciidoc
                ${newContent}
                \`\`\`
                
                Bitte überprüfen Sie die Änderungen und aktualisieren Sie die index.adoc Datei.`,
                labels: ['admin-list-update']
              });
            } 