name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: rust
          path: .
          token: ${{ secrets.GITHUB_TOKEN }}

  build-and-release:
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ needs.release-please.outputs.tag_name }}

      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-24.11

      - name: Build with Nix
        run: |
          nix-build -E '
            with import <nixpkgs> {};
            rustPlatform.buildRustPackage {
              pname = "azure-devops-admins";
              version = "${{ needs.release-please.outputs.tag_name }}";
              src = ./.;
              cargoLock.lockFile = ./Cargo.lock;
              nativeBuildInputs = [ pkg-config ];
              buildInputs = [ openssl ];
            }'
          cp result/bin/azure-devops-admins .

      - name: Upload Binary to Release
        uses: softprops/action-gh-release@v1
        with:
          files: azure-devops-admins
          tag_name: ${{ needs.release-please.outputs.tag_name }} 