name: Update Azure DevOps Admins PR

on:
  workflow_dispatch: # Erlaubt manuelle Ausführung

permissions: {} # remove default permissions

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # ratchet:actions/checkout@v4.2.2
        with:
          token: ${{ secrets.FINE_GRAINED_PAT }}

      - name: Download Admin Checker
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # ratchet:actions/upload-artifact@v4.6.2
        with:
          name: azure-devops-admins
          path: .

      - name: Make Binary Executable
        run: chmod +x azure-devops-admins

      - name: Run Admin Checker
        env:
          AZURE_DEVOPS_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}
        run: |
          ./azure-devops-admins
          if git diff --quiet index.adoc; then
            echo "No changes detected"
          else
            echo "ADMINS_CHANGED=true" >> $GITHUB_ENV
          fi

      - name: Create Pull Request
        if: env.ADMINS_CHANGED == 'true'
        uses: peter-evans/create-pull-request@4e1beaa7521e8b457b572c090b25bd3db56bf1c5 # ratchet:peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.FINE_GRAINED_PAT }}
          commit-message: Update Azure DevOps admin list
          title: Update Azure DevOps admin list
          body: |
            Automatische Aktualisierung der Azure DevOps Administrator Liste.

            Diese Änderung wurde automatisch durch den GitHub Action Workflow erstellt.
          branch: update-admin-list
          delete-branch: true
          labels: "automated-pr\nadmin-list-update "

