name: Update Azure DevOps Admins PR

on:
  schedule:
    - cron: '0 8 * * 1'  # Jeden Montag um 8:00 UTC
  workflow_dispatch:  # Erlaubt manuelle Ausführung

permissions: {}  # remove default permissions

jobs:
  create-pr:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.FINE_GRAINED_PAT }}

      - name: Setup Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Build and run admin checker
        env:
          AZURE_DEVOPS_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}
        run: |
          cargo run
          if git diff --quiet index.adoc; then
            echo "No changes detected"
          else
            echo "ADMINS_CHANGED=true" >> $GITHUB_ENV
          fi

      - name: Create Pull Request
        if: env.ADMINS_CHANGED == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.FINE_GRAINED_PAT }}
          commit-message: Update Azure DevOps admin list
          title: Update Azure DevOps admin list
          body: |
            Automatische Aktualisierung der Azure DevOps Administrator Liste.
            
            Diese Änderung wurde automatisch durch den GitHub Action Workflow erstellt.
          branch: update-admin-list
          delete-branch: true
          labels: |
            automated-pr
            admin-list-update 