name: Update Azure DevOps Admins PR

on:
  workflow_dispatch:

permissions: {} # remove default permissions

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # ratchet:actions/checkout@v4.2.2
        with:
          token: ${{ secrets.FINE_GRAINED_PAT }}

      - name: Download Admin Checker
        uses: actions/download-artifact@95815c38cf2ff2164869cbab79da8d1f422bc89e # ratchet:actions/download-artifact@v4.2.1
        with:
          name: azure-devops-admins
          github-token: ${{ secrets.FINE_GRAINED_PAT }}
          repository: ${{ github.repository }}
          run-id: 14538961115
          path: .

      - name: Make Binary Executable
        run: chmod +x azure-devops-admins

      - uses: cachix/install-nix-action@d1ca217b388ee87b2507a9a93bf01368bde7cec2 # ratchet:cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-24.11

      - name: Run Admin Checker
        env:
          AZURE_DEVOPS_PAT: ${{ secrets.AZURE_DEVOPS_PAT }}
        run: |
          nix-shell -p glibc openssl --run "
            ./azure-devops-admins
            if git diff --quiet index.adoc; then
              echo 'No changes detected'
            else
              echo 'ADMINS_CHANGED=true' >> \$GITHUB_ENV
              
            fi
            rm azure-devops-admins  # Remove the binary before creating the PR
          "

      - name: Create Pull Request
        if: env.ADMINS_CHANGED == 'true'
        uses: peter-evans/create-pull-request@271a8d0340265f705b14b6d32b9829c1cb33d45e # ratchet:peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.FINE_GRAINED_PAT }}
          commit-message: Update Azure DevOps admin list
          title: Update Azure DevOps admin list
          body: |
            Automatische Aktualisierung der Azure DevOps Administrator Liste.

            Diese Änderung wurde automatisch durch den GitHub Action Workflow erstellt.
          branch: update-admin-list
          delete-branch: true
          labels: "automated-pr\nadmin-list-update "

